// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

/**
import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import StickyController from "./sticky_controller"
application.register("sticky", StickyController)
 */
import { Application } from "@hotwired/stimulus"
import MenuController from "./menu_controller"

window.Stimulus = Application.start()
Stimulus.register("menu", MenuController)